name: Deploy UI

on:
  push:
    branches:
      - main
    paths:
     - "client/**"

defaults:
 run:
  working-directory: ./client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"
      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Build UI
        env:
          VITE_API_URL: ${{ secrets.API_URL }}
          CI: false
        run: npm i && npm run build
      - name: Deploy UI
        run: aws s3 sync dist/ s3://movielogger/ --delete
      - name: Invalidate CloudFront cache
        run: |
          # Get the CloudFront distribution ID from secrets or environment
          DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          
          echo "Creating CloudFront invalidation for distribution: $DISTRIBUTION_ID"
          
          # Create the invalidation - invalidate all paths to ensure fresh content
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text
          
          echo "CloudFront cache invalidation created successfully"